# Generated by Django 6.0.3 on 2026-04-16 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_academicyear_year'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentclasspromotion',
            old_name='is_to_class_the_current',
            new_name='has_promoted',
        ),
        migrations.RemoveField(
            model_name='studentclasspromotion',
            name='from_class',
        ),
        migrations.RemoveField(
            model_name='studentclasspromotion',
            name='from_year',
        ),
        migrations.RemoveField(
            model_name='studentclasspromotion',
            name='to_class',
        ),
        migrations.RemoveField(
            model_name='studentclasspromotion',
            name='year_year',
        ),
        migrations.AddField(
            model_name='studentclasspromotion',
            name='academic_year',
            field=models.ForeignKey(default=2016, on_delete=django.db.models.deletion.CASCADE, related_name='class_promotion_academic_year', to='academics.academicyear'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentclasspromotion',
            name='current_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_class_current_class', to='academics.schoolsupportedclasses'),
        ),
        migrations.AddField(
            model_name='studentclasspromotion',
            name='has_repeated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentclasspromotion',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentclasspromotion',
            name='is_initial_class',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentclasspromotion',
            name='previous_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_class_previous_class', to='academics.schoolsupportedclasses'),
        ),
        migrations.AddField(
            model_name='studentclasspromotion',
            name='upcoming_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_class_upcoming_class', to='academics.schoolsupportedclasses'),
        ),
    ]
