# Generated by Django 6.0.3 on 2026-03-31 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_parentprofile_access_token_and_more'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admission',
            name='parent_address',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='parent_email',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='parent_full_name',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='parent_occupation',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='parent_phone',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='parent_relationship',
        ),
        migrations.RemoveField(
            model_name='student',
            name='parent',
        ),
        migrations.AddField(
            model_name='admission',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='True once the admission has been verified and the student + parent accounts have been created.'),
        ),
        migrations.AddField(
            model_name='admission',
            name='parents_data',
            field=models.JSONField(default=list, help_text='JSON array of parent/guardian dicts. See Admission docstring for schema.'),
        ),
        migrations.AddField(
            model_name='admission',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions_verified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student',
            name='admission',
            field=models.OneToOneField(blank=True, help_text='Admission application that resulted in this student record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrolled_student', to='students.admission'),
        ),
        migrations.AlterField(
            model_name='student',
            name='district_of_origin',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(help_text='Auto-generated e.g. STD2025001', max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='StudentParentRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relationship', models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('legal_guardian', 'Legal Guardian'), ('uncle', 'Uncle'), ('aunt', 'Aunt'), ('grandparent', 'Grandparent'), ('sibling', 'Elder Sibling'), ('other', 'Other')], default='other', max_length=20)),
                ('access_token', models.CharField(help_text='Shared token among all parents of this student. Used as the parent portal login password.', max_length=64)),
                ('is_primary', models.BooleanField(default=False, help_text='The primary/emergency contact parent for this student.')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_relationships', to='accounts.parentprofile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_relationships', to='students.student')),
            ],
            options={
                'verbose_name': 'Student–Parent Relationship',
                'verbose_name_plural': 'Student–Parent Relationships',
                'ordering': ['student', '-is_primary', 'relationship'],
                'unique_together': {('student', 'parent')},
            },
        ),
    ]
