# Generated by Django 6.0.3 on 2026-04-06 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('assessments', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessment',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='academics.term'),
        ),
        migrations.AddField(
            model_name='assessmentclass',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_classes', to='assessments.assessment'),
        ),
        migrations.AddField(
            model_name='assessmentclass',
            name='invigilator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invigilated_classes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessmentclass',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_assessment_links', to='academics.schoolclass'),
        ),
        migrations.AddField(
            model_name='assessmentclass',
            name='school_stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='academics.schoolstream'),
        ),
        migrations.AddField(
            model_name='assessmentpassmark',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Head teacher or admin who approved this passmark', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pass_marks_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessmentpassmark',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pass_marks', to='assessments.assessment'),
        ),
        migrations.AddField(
            model_name='assessmentpassmark',
            name='set_by',
            field=models.ForeignKey(blank=True, help_text='The teacher who set this passmark', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pass_marks_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessmentpassmark',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_pass_marks', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='assessmentperformance',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='assessments.assessment'),
        ),
        migrations.AddField(
            model_name='assessmentperformance',
            name='entered_by',
            field=models.ForeignKey(blank=True, help_text='Teacher / staff who entered these marks', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performances_entered', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessmentperformance',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_performances', to='academics.schoolclass'),
        ),
        migrations.AddField(
            model_name='assessmentperformance',
            name='school_stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessment_performances', to='academics.schoolstream'),
        ),
        migrations.AddField(
            model_name='assessmentperformance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_performances', to='students.student'),
        ),
        migrations.AddField(
            model_name='assessmentperformance',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_performances', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='assessmentperformance',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='Head teacher / second marker who verified the marks', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performances_verified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessmentsubject',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_subjects', to='assessments.assessment'),
        ),
        migrations.AddField(
            model_name='assessmentsubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_assessment_links', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='assessmentteacher',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_teachers', to='assessments.assessment'),
        ),
        migrations.AddField(
            model_name='assessmentteacher',
            name='school_class',
            field=models.ForeignKey(blank=True, help_text='Class this teacher handled (invigilator / class_teacher)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_assessment_teachers', to='academics.schoolclass'),
        ),
        migrations.AddField(
            model_name='assessmentteacher',
            name='school_stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_assessment_teachers', to='academics.schoolstream'),
        ),
        migrations.AddField(
            model_name='assessmentteacher',
            name='subject',
            field=models.ForeignKey(blank=True, help_text='Subject this teacher is responsible for (marker / setter)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_assessment_teachers', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='assessmentteacher',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assessment_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='assessmentclass',
            unique_together={('assessment', 'school_class')},
        ),
        migrations.AlterUniqueTogether(
            name='assessmentpassmark',
            unique_together={('assessment', 'subject')},
        ),
        migrations.AlterUniqueTogether(
            name='assessmentperformance',
            unique_together={('assessment', 'student', 'subject')},
        ),
        migrations.AlterUniqueTogether(
            name='assessmentsubject',
            unique_together={('assessment', 'subject')},
        ),
        migrations.AlterUniqueTogether(
            name='assessmentteacher',
            unique_together={('assessment', 'teacher', 'role')},
        ),
    ]
