# Generated by Django 6.0.3 on 2026-04-01 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_assessmentclass_school_stream_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='duration_minutes',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='marking_scheme',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='paper_file',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='total_marks',
        ),
    ]
