# Generated by Django 6.0.3 on 2026-04-16 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_academicyear_year'),
        ('assessments', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessmentclass',
            options={'verbose_name': 'Assessment Class', 'verbose_name_plural': 'Assessment Classes'},
        ),
        migrations.AlterModelOptions(
            name='assessmentperformance',
            options={'ordering': ['assessment', 'student__last_name'], 'verbose_name': 'Assessment Performance', 'verbose_name_plural': 'Assessment Performances'},
        ),
        migrations.AlterModelOptions(
            name='assessmentsubject',
            options={'ordering': ['assessment'], 'verbose_name': 'Assessment Subject', 'verbose_name_plural': 'Assessment Subjects'},
        ),
        migrations.AlterModelOptions(
            name='assessmentteacher',
            options={'verbose_name': 'Assessment Teacher', 'verbose_name_plural': 'Assessment Teachers'},
        ),
        migrations.RenameField(
            model_name='assessmentclass',
            old_name='students_invited',
            new_name='students_attended',
        ),
        migrations.RenameField(
            model_name='assessmentperformance',
            old_name='remarks',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='assessmentsubject',
            old_name='total_marks',
            new_name='passmark',
        ),
        migrations.AlterUniqueTogether(
            name='assessmentclass',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='assessmentperformance',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='assessmentteacher',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='assessmentsubject',
            name='paper_file',
        ),
        migrations.RemoveField(
            model_name='assessmentsubject',
            name='sort_order',
        ),
        migrations.AlterField(
            model_name='assessmentclass',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_assessment_links', to='academics.schoolsupportedclasses'),
        ),
        migrations.AlterField(
            model_name='assessmentperformance',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_performances', to='academics.subject'),
        ),
        migrations.RemoveField(
            model_name='assessmentclass',
            name='class_remarks',
        ),
        migrations.RemoveField(
            model_name='assessmentclass',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='assessmentclass',
            name='invigilator',
        ),
        migrations.RemoveField(
            model_name='assessmentclass',
            name='school_stream',
        ),
        migrations.RemoveField(
            model_name='assessmentclass',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='assessmentclass',
            name='students_absent',
        ),
        migrations.RemoveField(
            model_name='assessmentclass',
            name='students_sat',
        ),
        migrations.RemoveField(
            model_name='assessmentclass',
            name='venue',
        ),
        migrations.RemoveField(
            model_name='assessmentperformance',
            name='absent_reason',
        ),
        migrations.RemoveField(
            model_name='assessmentperformance',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='assessmentperformance',
            name='is_absent',
        ),
        migrations.RemoveField(
            model_name='assessmentperformance',
            name='is_pass',
        ),
        migrations.RemoveField(
            model_name='assessmentperformance',
            name='nursery_rating',
        ),
        migrations.RemoveField(
            model_name='assessmentperformance',
            name='school_stream',
        ),
        migrations.RemoveField(
            model_name='assessmentperformance',
            name='total_marks',
        ),
        migrations.RemoveField(
            model_name='assessmentteacher',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='assessmentteacher',
            name='role',
        ),
        migrations.RemoveField(
            model_name='assessmentteacher',
            name='school_stream',
        ),
    ]
