# Generated by Django 6.0.3 on 2026-04-18 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_alter_assessmentclass_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assessmentsubject',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='AssessmentTotalMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_mark', models.DecimalField(decimal_places=1, help_text='The total mark value. percentage → e.g. 50.0 (means 50%). absolute   → e.g. 45.0 (means 45 marks).', max_digits=6)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='total_mark', to='assessments.assessment')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_total_mark', to='assessments.assessmentsubject')),
            ],
            options={
                'verbose_name': 'Assessment Total Mark',
                'verbose_name_plural': 'Assessment Total Marks',
                'ordering': ['assessment'],
            },
        ),
        migrations.DeleteModel(
            name='AssessmentPassMark',
        ),
    ]
