# Generated by Django 6.0.3 on 2026-04-18 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_academicyear_year'),
        ('assessments', '0004_alter_assessmentsubject_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentsubject',
            name='assessment_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessment_subject', to='academics.schoolsupportedclasses'),
        ),
    ]
