# Generated by Django 6.0.3 on 2026-04-18 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_academicyear_year'),
        ('assessments', '0005_assessmentsubject_assessment_class'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assessmentsubject',
            unique_together={('assessment', 'assessment_class', 'subject')},
        ),
    ]
