# Generated by Django 6.0.3 on 2026-04-19 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_academicyear_year'),
        ('assessments', '0006_alter_assessmentsubject_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentteacher',
            name='school_class',
            field=models.ForeignKey(blank=True, help_text='Class this teacher handled (invigilator / class_teacher)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_assessment_teachers', to='academics.schoolsupportedclasses'),
        ),
    ]
