# Generated by Django 6.0.3 on 2026-04-06 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('assessments', '0002_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentFees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount in Uganda Shillings (UGX)', max_digits=12, null=True)),
                ('due_date', models.DateField(blank=True, help_text='Payment deadline for this assessment fee', null=True)),
                ('assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessment_fee', to='assessments.assessment')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_assessments_generated', to=settings.AUTH_USER_MODEL)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_fee_assessments', to='academics.term')),
            ],
            options={
                'verbose_name': 'Assessment Fee',
                'verbose_name_plural': 'Assessment Fees',
                'ordering': ['term__name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolFees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fees_type', models.CharField(choices=[('tuition', 'Tuition Fees'), ('development', 'Development / Building Levy'), ('activity', 'Activity / Games Fees'), ('lunch', 'Lunch / Feeding Fees'), ('transport', 'Transport / Bus Fees'), ('uniform', 'Uniform Fees'), ('boarding', 'Boarding Fees'), ('pta', 'PTA Contribution'), ('exam', 'Examination Fees'), ('admission', 'Admission / Registration Fees'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(blank=True, help_text='Optional label when fees_type alone is ambiguous', max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount in Uganda Shillings (UGX)', max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, help_text='Payment deadline for this fee', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='academics.term')),
            ],
            options={
                'verbose_name': 'School Fees Structure',
                'verbose_name_plural': 'School Fees Structures',
                'ordering': ['term', 'fees_type'],
            },
        ),
        migrations.CreateModel(
            name='FeesPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receipt_number', models.CharField(help_text='Auto-generated e.g. RCP2025001', max_length=30, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount paid in UGX', max_digits=12)),
                ('payment_date', models.DateField()),
                ('assessment_fees', models.ForeignKey(blank=True, help_text='Populated when paying an assessment fee line', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessment_fee_transactions', to='fees.assessmentfees')),
                ('handled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_handled', to=settings.AUTH_USER_MODEL)),
                ('school_class', models.ForeignKey(help_text="Student's class AT THE TIME of payment", on_delete=django.db.models.deletion.CASCADE, related_name='fees_payment_records', to='academics.schoolsupportedclasses')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees_payment_records', to='students.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees_payment_records', to='academics.term')),
                ('school_fees', models.ForeignKey(blank=True, help_text='Populated when paying a school fee line', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_payment_transactions', to='fees.schoolfees')),
            ],
            options={
                'verbose_name': 'Fees Payment',
                'verbose_name_plural': 'Fees Payments',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SchoolScholasticRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_name', models.CharField(help_text='E.g. "Broom", "Graph book", "A4 Ream"', max_length=150)),
                ('quantity', models.PositiveIntegerField(help_text='Number of units required per student')),
                ('unit', models.CharField(choices=[('pieces', 'Pieces'), ('reams', 'Reams'), ('litres', 'Litres'), ('kg', 'Kilograms'), ('pairs', 'Pairs'), ('sets', 'Sets'), ('other', 'Other')], default='pieces', max_length=20)),
                ('monetary_value', models.DecimalField(decimal_places=2, help_text='UGX cash equivalent for the FULL required quantity. Used when student pays cash instead of bringing items.', max_digits=10)),
                ('description', models.TextField(blank=True, help_text='Extra instructions e.g. "Short-handle brooms only"')),
                ('is_active', models.BooleanField(default=True)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholastic_requirements', to='academics.term')),
            ],
            options={
                'verbose_name': 'Scholastic Requirement',
                'verbose_name_plural': 'Scholastic Requirements',
                'ordering': ['term', 'item_name'],
            },
        ),
        migrations.CreateModel(
            name='StudentClassPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_year', models.CharField(help_text='4-digit year the student WAS IN from_class e.g. 2022', max_length=4)),
                ('to_year', models.CharField(help_text='4-digit year the student MOVED INTO to_class e.g. 2023', max_length=4)),
                ('is_to_class_the_current', models.BooleanField(default=False, help_text='True only on the most recent promotion row')),
                ('from_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions_from_students', to='academics.schoolsupportedclasses')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_promotions', to='students.student')),
                ('to_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions_to_students', to='academics.schoolsupportedclasses')),
            ],
            options={
                'verbose_name': 'Student Class Promotion',
                'verbose_name_plural': 'Student Class Promotions',
                'ordering': ['student', 'from_year'],
            },
        ),
        migrations.CreateModel(
            name='FeesClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment_fee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessment_fee_affected_class', to='fees.assessmentfees')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affected_fees_class', to='academics.schoolsupportedclasses')),
                ('fees', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='affected_school_class', to='fees.schoolfees')),
            ],
            options={
                'verbose_name': 'Fees Class Assignment',
                'verbose_name_plural': 'Fees Class Assignments',
                'unique_together': {('assessment_fee', 'school_class'), ('fees', 'school_class')},
            },
        ),
        migrations.CreateModel(
            name='ScholasticRequirementClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholastic_requirements', to='academics.schoolsupportedclasses')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_classes', to='fees.schoolscholasticrequirements')),
            ],
            options={
                'verbose_name': 'Scholastic Requirement Class Assignment',
                'verbose_name_plural': 'Scholastic Requirement Class Assignments',
                'unique_together': {('requirement', 'school_class')},
            },
        ),
        migrations.CreateModel(
            name='StudentFeesPaymentsStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_type', models.CharField(choices=[('school', 'School Fees Payment'), ('assessment', 'Assessment Fees Payment')], max_length=25)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, help_text='Cumulative amount paid so far in UGX', max_digits=12)),
                ('amount_balance', models.DecimalField(decimal_places=2, help_text='Remaining balance in UGX', max_digits=12)),
                ('fully_paid', models.BooleanField(default=False)),
                ('fully_paid_on', models.DateField(blank=True, null=True)),
                ('assessment_fees', models.ForeignKey(blank=True, help_text='Populated when tracking an assessment fee balance', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_assessment_statuses', to='fees.assessmentfees')),
                ('school_class', models.ForeignKey(help_text="Student's class when this status row was created", on_delete=django.db.models.deletion.CASCADE, related_name='fee_status_records', to='academics.schoolsupportedclasses')),
                ('school_fees', models.ForeignKey(blank=True, help_text='Populated when tracking a school fee balance', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_payment_statuses', to='fees.schoolfees')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_payment_status_records', to='students.student')),
            ],
            options={
                'verbose_name': 'Student Fees Payment Status',
                'verbose_name_plural': 'Student Fees Payment Statuses',
                'ordering': ['student', 'payment_type'],
                'unique_together': {('student', 'assessment_fees'), ('student', 'school_fees')},
            },
        ),
        migrations.CreateModel(
            name='StudentScholasticRequirementStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_brought', models.PositiveIntegerField(default=0, help_text='Total physical units brought by the student so far')),
                ('last_brought_on', models.DateField(blank=True, help_text='Date the most recent physical items were received', null=True)),
                ('amount_paid_ugx', models.DecimalField(decimal_places=2, default=0, help_text='Total cash paid so far in UGX toward this requirement', max_digits=10)),
                ('last_paid_on', models.DateField(blank=True, help_text='Date of the most recent cash payment', null=True)),
                ('amount_balance_ugx', models.DecimalField(decimal_places=2, default=0, help_text='Remaining balance in UGX after crediting both physical and cash', max_digits=10)),
                ('fully_met', models.BooleanField(default=False, help_text='True when combined physical + cash covers the full requirement')),
                ('fully_met_on', models.DateField(blank=True, help_text='Date the requirement was fully satisfied', null=True)),
                ('notes', models.TextField(blank=True, help_text='E.g. "Brought 1 broom, paid UGX 1,500 for the second"')),
                ('recorded_by', models.ForeignKey(blank=True, help_text='Staff member who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scholastic_statuses_recorded', to=settings.AUTH_USER_MODEL)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_statuses', to='fees.schoolscholasticrequirements')),
                ('school_class', models.ForeignKey(help_text="Student's class when requirement was assigned", on_delete=django.db.models.deletion.CASCADE, related_name='scholastic_student_statuses', to='academics.schoolsupportedclasses')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholastic_requirement_statuses', to='students.student')),
            ],
            options={
                'verbose_name': 'Student Scholastic Requirement Status',
                'verbose_name_plural': 'Student Scholastic Requirement Statuses',
                'ordering': ['student', 'requirement__term', 'requirement__item_name'],
                'unique_together': {('student', 'requirement')},
            },
        ),
    ]
