# Generated by Django 6.0.3 on 2026-04-19 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_academicyear_year'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolannouncement',
            name='school_stream',
        ),
        migrations.AlterField(
            model_name='schoolannouncement',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='academics.schoolsupportedclasses'),
        ),
    ]
