# Generated by Django 6.0.3 on 2026-03-30 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertypepermission',
            name='action_effect',
            field=models.CharField(blank=True, choices=[('can_my', 'Can My  – own records only'), ('can_all', 'Can All – all records')], default=None, max_length=10, null=True),
        ),
    ]
