# Generated by Django 6.0.3 on 2026-03-25 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('legal_guardian', 'Legal Guardian'), ('uncle', 'Uncle'), ('aunt', 'Aunt'), ('grandparent', 'Grandparent'), ('sibling', 'Elder Sibling'), ('other', 'Other')], max_length=20)),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('employer', models.CharField(blank=True, max_length=200)),
                ('work_phone', models.CharField(blank=True, max_length=15)),
                ('work_address', models.TextField(blank=True)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('sub_county', models.CharField(blank=True, max_length=100)),
                ('village', models.CharField(blank=True, max_length=100)),
                ('religion', models.CharField(blank=True, max_length=50)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=15)),
                ('emergency_contact_rel', models.CharField(blank=True, max_length=50, verbose_name='Emergency contact relationship')),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'parent'}, on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parent Profile',
                'verbose_name_plural': 'Parent Profiles',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(help_text='Auto-generated or assigned employee number (e.g. EMP20250001)', max_length=20, unique=True)),
                ('role', models.CharField(choices=[('head_teacher', 'Head Teacher'), ('deputy_head', 'Deputy Head Teacher'), ('teacher', 'Class Teacher'), ('subject_teacher', 'Subject Teacher'), ('bursar', 'Bursar'), ('secretary', 'School Secretary'), ('librarian', 'Librarian'), ('lab_technician', 'Lab Technician'), ('nurse', 'School Nurse / Health Worker'), ('security', 'Security Personnel'), ('cleaner', 'Cleaner / Janitor'), ('driver', 'Driver'), ('cook', 'Cook / Catering Staff'), ('it_officer', 'IT Officer'), ('other', 'Other')], max_length=20)),
                ('employment_type', models.CharField(choices=[('permanent', 'Permanent'), ('contract', 'Contract'), ('part_time', 'Part-Time'), ('volunteer', 'Volunteer'), ('intern', 'Intern')], default='permanent', max_length=15)),
                ('date_joined', models.DateField()),
                ('date_left', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('qualification', models.CharField(blank=True, choices=[('ptc', 'Primary Teachers Certificate (PTC)'), ('grade3', 'Grade III Certificate'), ('diploma', 'Diploma in Education'), ('degree', 'Bachelor of Education (B.Ed)'), ('pgde', 'PGDE'), ('masters', 'Masters in Education'), ('certificate', 'Certificate (Non-Education)'), ('diploma_other', 'Diploma (Non-Education)'), ('bachelors', 'Bachelors (Non-Education)'), ('none', 'No Formal Qualification'), ('other', 'Other')], max_length=20)),
                ('specialization', models.CharField(blank=True, help_text='e.g. Mathematics, English, Early Childhood', max_length=100)),
                ('is_class_teacher', models.BooleanField(default=False, help_text='Assigned as a class / form teacher?')),
                ('nssf_number', models.CharField(blank=True, max_length=20, verbose_name='NSSF Number')),
                ('tin_number', models.CharField(blank=True, max_length=20, verbose_name='TIN Number')),
                ('salary_scale', models.CharField(blank=True, max_length=50)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('bank_account', models.CharField(blank=True, max_length=30)),
                ('bio', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True, help_text='Internal HR notes — not visible to the employee')),
                ('signature', models.ImageField(blank=True, help_text='Used on report cards and official letters', null=True, upload_to='staff/signatures/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_managed', models.ForeignKey(blank=True, help_text='Class this teacher is directly responsible for', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_teacher', to='academics.schoolclass')),
                ('user', models.OneToOneField(limit_choices_to={'user_type__in': ('teacher', 'staff', 'admin')}, on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Profile',
                'verbose_name_plural': 'Staff Profiles',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
    ]
