# Generated by Django 6.0.3 on 2026-04-06 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(help_text='Opaque token used as the parent portal login password. Generated once at account creation. Shared across all parents of the same student via StudentParentRelationship.', max_length=64)),
                ('relationship', models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('legal_guardian', 'Legal Guardian'), ('uncle', 'Uncle'), ('aunt', 'Aunt'), ('grandparent', 'Grandparent'), ('sibling', 'Elder Sibling'), ('other', 'Other')], max_length=20)),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('employer', models.CharField(blank=True, max_length=200)),
                ('work_phone', models.CharField(blank=True, max_length=15)),
                ('work_address', models.TextField(blank=True)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('sub_county', models.CharField(blank=True, max_length=100)),
                ('village', models.CharField(blank=True, max_length=100)),
                ('religion', models.CharField(blank=True, max_length=50)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=15)),
                ('emergency_contact_rel', models.CharField(blank=True, max_length=50, verbose_name='Emergency contact relationship')),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Parent Profile',
                'verbose_name_plural': 'Parent Profiles',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(help_text='Auto-generated e.g. EMP20250001', max_length=20, unique=True)),
                ('role', models.CharField(choices=[('head_teacher', 'Head Teacher'), ('deputy_head', 'Deputy Head Teacher'), ('teacher', 'Class Teacher'), ('subject_teacher', 'Subject Teacher'), ('bursar', 'Bursar'), ('secretary', 'School Secretary'), ('librarian', 'Librarian'), ('lab_technician', 'Lab Technician'), ('nurse', 'School Nurse / Health Worker'), ('security', 'Security Personnel'), ('cleaner', 'Cleaner / Janitor'), ('driver', 'Driver'), ('cook', 'Cook / Catering Staff'), ('it_officer', 'IT Officer'), ('other', 'Other')], max_length=20)),
                ('employment_type', models.CharField(choices=[('permanent', 'Permanent'), ('contract', 'Contract'), ('part_time', 'Part-Time'), ('volunteer', 'Volunteer'), ('intern', 'Intern')], default='permanent', max_length=15)),
                ('date_joined', models.DateField()),
                ('date_left', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('qualification', models.CharField(blank=True, choices=[('ptc', 'Primary Teachers Certificate (PTC)'), ('grade3', 'Grade III Certificate'), ('diploma', 'Diploma in Education'), ('degree', 'Bachelor of Education (B.Ed)'), ('pgde', 'PGDE'), ('masters', 'Masters in Education'), ('certificate', 'Certificate (Non-Education)'), ('diploma_other', 'Diploma (Non-Education)'), ('bachelors', 'Bachelors (Non-Education)'), ('none', 'No Formal Qualification'), ('other', 'Other')], max_length=20)),
                ('specialization', models.CharField(blank=True, max_length=100)),
                ('is_class_teacher', models.BooleanField(default=False)),
                ('nssf_number', models.CharField(blank=True, max_length=20)),
                ('tin_number', models.CharField(blank=True, max_length=20)),
                ('salary_scale', models.CharField(blank=True, max_length=50)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('bank_account', models.CharField(blank=True, max_length=30)),
                ('bio', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('signature', models.ImageField(blank=True, null=True, upload_to='staff/signatures/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Staff Profile',
                'verbose_name_plural': 'Staff Profiles',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
    ]
