# Generated by Django 6.0.3 on 2026-03-31 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentprofile',
            name='access_token',
            field=models.CharField(default=1, help_text='Opaque token used as the parent portal login password. Generated once at account creation. Shared across all parents of the same student via StudentParentRelationship.', max_length=64, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='class_managed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_teacher', to='academics.schoolclass'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='employee_id',
            field=models.CharField(help_text='Auto-generated e.g. EMP20250001', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='is_class_teacher',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='nssf_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='staff/signatures/'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='specialization',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='tin_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
