# Generated by Django 6.0.3 on 2026-04-06 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_staffprofile_school_stream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentprofile',
            name='access_token',
            field=models.CharField(help_text='Opaque token used as the parent portal login password. Generated once at account creation. Shared across all parents of the same student via StudentParentRelationship.', max_length=64),
        ),
    ]
