# Generated by Django 6.0.3 on 2026-03-29 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_permission_usertypepermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('head_teacher', 'Head Teacher'), ('deputy_head_teacher', 'Teacher'), ('class_teacher', 'Support Staff'), ('subject_teacher', 'Administrator'), ('admin', 'Administrator'), ('bursar', 'Bursar'), ('secretary', 'Secretary'), ('librarian', 'Libralian'), ('lab_technician', 'Lab Technician'), ('school_nurse', 'School Nurse'), ('security_parsonnel', 'Security Parsonnel'), ('cleaner', 'Cleaner or Janitor'), ('driver', 'School Driver'), ('cook', 'Cook'), ('it_officer', 'IT Officer'), ('metron', 'Metron'), ('dean', 'Dean Of Students'), ('others', 'Others')], max_length=100, null=True),
        ),
    ]
