# Generated by Django 6.0.3 on 2026-03-30 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_customuser_role'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='usertypepermission',
            name='unique_permission_per_user_type',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
        migrations.RemoveField(
            model_name='usertypepermission',
            name='permission',
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
        migrations.DeleteModel(
            name='UserTypePermission',
        ),
    ]
