# Generated by Django 6.0.3 on 2026-03-25 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='E.g. English Language, Mathematics, Science, SST, MTC, CRE, IRE', max_length=100)),
                ('code', models.CharField(help_text='Short code e.g. ENG, MAT, SCI, SST, MTC, CRE, IRE, LIT', max_length=10, unique=True)),
                ('level', models.CharField(choices=[('nursery', 'Nursery (Baby – Top Class)'), ('lower_primary', 'Lower Primary (P1 – P3)'), ('upper_primary', 'Upper Primary (P4 – P7)'), ('all', 'All Levels')], help_text='Which school level this subject belongs to', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_compulsory', models.BooleanField(default=True, help_text='Is this subject compulsory for all students at the level?')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Order in which subject appears on report cards')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.CharField(choices=[('baby', 'Baby Class'), ('middle', 'Middle Class'), ('top', 'Top Class'), ('p1', 'Primary One (P1)'), ('p2', 'Primary Two (P2)'), ('p3', 'Primary Three (P3)'), ('p4', 'Primary Four (P4)'), ('p5', 'Primary Five (P5)'), ('p6', 'Primary Six (P6)'), ('p7', 'Primary Seven (P7)')], max_length=10)),
                ('stream', models.CharField(blank=True, help_text='Stream / section e.g. A, B, C. Leave blank if no streaming.', max_length=5)),
                ('section', models.CharField(choices=[('nursery', 'Nursery'), ('primary', 'Primary')], max_length=10)),
                ('capacity', models.PositiveIntegerField(default=45, help_text='Maximum number of students allowed in this class')),
                ('classroom', models.CharField(blank=True, help_text='Room number or name e.g. Room 4, Block B', max_length=50)),
                ('academic_year', models.CharField(help_text='Format: 2025/2026', max_length=9)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
                'ordering': ['section', 'level', 'stream'],
                'unique_together': {('level', 'stream', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.IntegerField(choices=[(1, 'Term 1'), (2, 'Term 2'), (3, 'Term 3')], verbose_name='Term')),
                ('start_date', models.DateField(help_text='First day of the term (school opens)')),
                ('end_date', models.DateField(help_text='Last day of normal lessons before EOT exams')),
                ('is_current', models.BooleanField(default=False, help_text='Only one term should be marked current at a time')),
                ('bot_start_date', models.DateField(blank=True, help_text='Beginning of Term exam start date', null=True, verbose_name='BOT Exam Start')),
                ('bot_end_date', models.DateField(blank=True, help_text='Beginning of Term exam end date', null=True, verbose_name='BOT Exam End')),
                ('mot_start_date', models.DateField(blank=True, help_text='Middle of Term exam start date', null=True, verbose_name='MOT Exam Start')),
                ('mot_end_date', models.DateField(blank=True, help_text='Middle of Term exam end date', null=True, verbose_name='MOT Exam End')),
                ('eot_start_date', models.DateField(blank=True, help_text='End of Term exam start date', null=True, verbose_name='EOT Exam Start')),
                ('eot_end_date', models.DateField(blank=True, help_text='End of Term exam end date', null=True, verbose_name='EOT Exam End')),
                ('closing_date', models.DateField(blank=True, help_text='Last day students are in school (after EOT exams finish)', null=True)),
                ('opening_date', models.DateField(blank=True, help_text='Date school reopens for the NEXT term', null=True)),
                ('has_holiday_studies', models.BooleanField(default=False, help_text='Were selected classes called back for holiday coaching?')),
                ('holiday_study_start', models.DateField(blank=True, help_text='Date selected classes return for holiday coaching', null=True)),
                ('holiday_study_end', models.DateField(blank=True, help_text='Last day of holiday coaching', null=True)),
                ('holiday_study_note', models.TextField(blank=True, help_text='Instructions for parents e.g. bring all books, report by 8:00 am, uniform required.')),
                ('long_holiday_start', models.DateField(blank=True, help_text='Date the full holiday begins for everyone. Auto-set to day after holiday_study_end when has_holiday_studies=True, otherwise same as closing_date.', null=True)),
                ('holiday_study_classes', models.ManyToManyField(blank=True, help_text='Classes attending holiday studies e.g. P6, P7', related_name='holiday_study_terms', to='academics.schoolclass')),
            ],
            options={
                'verbose_name': 'Term',
                'verbose_name_plural': 'Terms',
                'ordering': ['-start_date', 'name'],
                'unique_together': {('name', 'start_date')},
            },
        ),
        migrations.CreateModel(
            name='ClassSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='academics.schoolclass')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='academics.subject')),
            ],
            options={
                'verbose_name': 'Class Subject',
                'verbose_name_plural': 'Class Subjects',
                'ordering': ['school_class', 'subject__sort_order'],
                'unique_together': {('school_class', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='TeacherSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_primary', models.BooleanField(default=False, help_text="Is this the teacher's main / specialist subject?")),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_teachers', to='academics.subject')),
            ],
            options={
                'verbose_name': 'Teacher Subject',
                'verbose_name_plural': 'Teacher Subjects',
                'ordering': ['-is_primary'],
                'unique_together': {('subject',)},
            },
        ),
        migrations.CreateModel(
            name='TeacherClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('periods_per_week', models.PositiveIntegerField(default=5, help_text='Number of teaching periods per week')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_teacher_assignments', to='academics.schoolclass')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to='academics.subject')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to='academics.term')),
            ],
            options={
                'verbose_name': 'Teacher Class Assignment',
                'verbose_name_plural': 'Teacher Class Assignments',
                'ordering': ['term', 'school_class', 'subject'],
                'unique_together': {('school_class', 'subject', 'term')},
            },
        ),
    ]
