# Generated by Django 6.0.3 on 2026-04-07 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teachersubject',
            unique_together=set(),
        ),
    ]
