# Generated by Django 6.0.3 on 2026-04-01 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_classsubject_school_stream_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolclass',
            old_name='level_type',
            new_name='section',
        ),
    ]
