# Generated by Django 6.0.3 on 2026-04-16 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_teachersubject_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='year',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
